import Head from "next/head";
import SearchBar from "./components/Search";
import MainView, { type User } from "./components/MainView";
import { useState } from "react";

export default function Home() {
	const [users, setUsers] = useState([{
		profileImage: "https://avatars.githubusercontent.com/u/107800884?v=4",
		id: "@FadedBronze",	
		websiteUrl: "https://samyat.netlify.app",
		repoCount: 387,
		commitCount: 16,
		frameworks: [["React", 3], ["Express", 5]],
		languages: [["Typescript", 3], ["Javascript", 4], ["Kotlin", 5], ["Java", 6]],
	}, {
		profileImage: "https://avatars.githubusercontent.com/u/45637546?v=4",
		id: "@Dragola",	
		repoCount: 363,
		commitCount: 18,
		frameworks: [["React", 3], ["Express", 5]],
		languages: [["Typescript", 3], ["Javascript", 4], ["Kotlin", 5], ["Java", 6]],
	}])	

	const [activeUser, setActiveUser] = useState(users[0]!.id)	

	const user = users.find(({id}) => id === activeUser)!;

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-screen h-screen bg-black flex justify-center items-center">
				<div className="w-2/3 flex gap-8 flex-col">
					<SearchBar activeUser={activeUser} setActiveUser={setActiveUser} users={users}></SearchBar>
					<div>
						<MainView
							commitCount={user.commitCount}
							repoCount={user.repoCount}
							websiteUrl={user.websiteUrl}
							frameworks={user.frameworks}
							languages={user.languages}
							id={user.id}
							profileImage={user.profileImage}
						></MainView>
					</div>
				</div>
			</div>
		</>
	);
}
